import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/header";
import { Footer } from "./_components/footer";
import { ReduxProvider } from "@/provider/redux-provider";
import { NextAuthProvider } from "@/provider/next-auth-provider";
// import FlareCursor from "@/component/flare-cursor";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ReduxProvider>
            <div className="flex h-screen flex-col justify-between">
              <div>
                <Header />
                {/* <FlareCursor /> */}
                {children}
              </div>
              <Footer />
            </div>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
